####  APPLICATION NAME  ####
spring.application.name=account-management
server.servlet.context-path=/account-management

app.base-url=${BASE_URL}

####  SERVER PORT ####
server.port=${SERVER_PORT:8085}

####  DATABASE DRIVER  ####
spring.datasource.driver-class-name=org.postgresql.Driver

####  LIQUIBASE  ####
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

#### SQL ####
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

#### GRPC ####
grpc.client.auth-server.negotiationType=plaintext
grpc.client.auth-server.enableKeepAlive=true

###------------------------------
### CLIENT CREDENTIALS
###------------------------------

mobility.oauth2.resources.auth-server-grpc=urn:mobility:auth-server

### GRPC CALLS TO AUTH SERVER
spring.security.oauth2.client.registration.auth-server-grpc.provider=auth-server
spring.security.oauth2.client.registration.auth-server-grpc.client-id=mobility-api
spring.security.oauth2.client.registration.auth-server-grpc.client-secret=thes333crEt
spring.security.oauth2.client.registration.auth-server-grpc.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.auth-server-grpc.client-authentication-method=client_secret_basic
spring.security.oauth2.client.registration.auth-server-grpc.scope=INTERNAL_SERVICE

##------------------------------
### INCOMING JWT TOKEN VALIDATION
###------------------------------
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://${AUTH_SERVER_URL:localhost}:9000/auth-server
spring.security.oauth2.resourceserver.jwt.audiences[0]=urn:mobility:account-management
spring.security.oauth2.resourceserver.jwt.audiences[1]=urn:mobility:public-api

### OAUTH 2 CLIENT
spring.security.oauth2.client.provider.auth-server.token-uri=http://${AUTH_SERVER_URL:localhost}:9000/auth-server/oauth2/token

#### REDIS ####
spring.data.redis.timeout=${REDIS_TIMEOUT:1s}
spring.data.redis.connect-timeout=${REDIS_CONNECT_TIMEOUT:1s}
spring.cache.redis.time-to-live=10m
app.cache.key-prefix=${ENVIRONMENT:dev}:${spring.application.name}

#### SECURITY ####
spring.security.oauth2.client.registration.mobility-api.scope=INTERNAL_SERVICE
spring.security.oauth2.client.registration.mobility-api.provider=auth-server
spring.security.oauth2.client.registration.mobility-api.client-id=mobility-api
spring.security.oauth2.client.registration.mobility-api.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.mobility-api.client-authentication-method=client_secret_basic

#### RABBITMQ ####

# CONNECT
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.password=${RABBITMQ_PASS}
spring.rabbitmq.virtual-host=${RABBITMQ_VHOST:/mobility}

# RELIABILITY
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true
spring.rabbitmq.connection-timeout=60000
spring.rabbitmq.requested-heartbeat=60