#### DATABASE CREDENTIALS ####
spring.datasource.url=jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:4567}/${DATABASE_NAME:accounts-db}
spring.datasource.username=${DATABASE_USERNAME:theodore}
spring.datasource.password=${DATABASE_PASSWORD:theo7272}

#### REDIS ####
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.username=${REDIS_USERNAME:user49}
spring.data.redis.password=${REDIS_PASSWORD:red!!spvvvvss}
spring.data.redis.ssl.enabled=false

#### MISC ####
slow.threshold=500

#### JWT BUILDERS ####
security.jwt.email.secret-base64=VvXv8GydOy2C9VkRSn3xAGEyzd/lklqB59H6EH5Bkc8=
security.jwt.email.ttl=3m

#### GRPC ####
grpc.client.auth-server.address=static://${AUTH_SERVER_URL:localhost}:9001

#### RABBITMQ ####
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:mobilityqueueuser}
spring.rabbitmq.password=${RABBITMQ_PASS:Strong-password1}


######## LOGS ########

#### DEFAULT LOGGING ####
logging.level.com.theodore=INFO
logging.pattern.console=${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
#### ROOT ####
logging.level.root=INFO
#### SPRING ####
logging.level.org.springframework=WARN
logging.level.org.springframework.boot.autoconfigure=WARN
logging.level.org.springframework.context=WARN
#### SECURITY ####
logging.level.org.springframework.security=DEBUG
#### DATABASE ####
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type.descriptor.sql=ERROR