#### REDIS ####
spring.data.redis.ssl.enabled=true
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.username=${REDIS_USERNAME}
spring.data.redis.password=${REDIS_PASSWORD}

#### DATABASE CREDENTIALS ####
spring.datasource.url=jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

#### SQL ####
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

#### SECURITY ####
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${OAUTH2_LOCATION}
spring.security.oauth2.client.registration.mobility-api.client-secret=${CLIENT_SECRET}
spring.security.oauth2.client.provider.auth-server.token-uri=${TOKEN_PROVIDER}
#### JWT BUILDERS ####
security.jwt.email.secret-base64=${JWT_SECRET}
security.jwt.email.ttl=3m

#### GRPC ####
grpc.client.auth-server.address=${GRPC_AUTH_SERVER}

#### AUTH SERVER ####
spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH_SERVER}